import type { Metadata } from 'next';
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from '@/components/Header/Header';
import HideFooter from '@/components/Hidefooter/HideFooter';
import '@/styles/Global.module.scss'
  

export const metadata: Metadata = {
    title: 'Client',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Header />
                <main>{children}</main>
                <HideFooter />
            </body>
        </html>
    );
}
