import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css"; // Import đúng chỗ
import "@/styles/Global.scss";
import Header from "@/components/Header/Header";
import HideFooter from "@/components/Hidefooter/HideFooter";


export const metadata: Metadata = {
  title: "Client",
  description: "Generated by create next app",
  icons: {
    icon: "/img/favicon.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header />
        <main>{children}</main>
        <HideFooter />
      </body>
    </html>
  );
}
